# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rb-skypemac"
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Evan Light"]
  s.date = "2012-02-05"
  s.description = "Ruby interface to Skype on Mac OS X"
  s.email = "sleight42@gmail.com"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "History.txt",
    "Manifest.txt",
    "Rakefile",
    "VERSION",
    "lib/rb-skypemac.rb",
    "lib/rb-skypemac/call.rb",
    "lib/rb-skypemac/chat.rb",
    "lib/rb-skypemac/group.rb",
    "lib/rb-skypemac/iam.rb",
    "lib/rb-skypemac/skype.rb",
    "lib/rb-skypemac/user.rb",
    "lib/rb-skypemac/version.rb",
    "scripts/txt2html",
    "setup.rb",
    "test/test_call.rb",
    "test/test_chat.rb",
    "test/test_group.rb",
    "test/test_helper.rb",
    "test/test_rb-skypemac.rb",
    "test/test_skype.rb",
    "test/test_user.rb",
    "website/index.html",
    "website/index.txt",
    "website/javascripts/rounded_corners_lite.inc.js",
    "website/stylesheets/screen.css",
    "website/template.rhtml"
  ]
  s.homepage = "http://rb-skypemac.rubyforge.org"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Ruby interface to Skype on Mac OS X"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rb-appscript>, [">= 0.3.0"])
      s.add_runtime_dependency(%q<hoe>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rb-appscript>, [">= 0.3.0"])
      s.add_dependency(%q<hoe>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rb-appscript>, [">= 0.3.0"])
    s.add_dependency(%q<hoe>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

